### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by KnutZuidema** [Fachschaft5/fs5bot#5]
Using a linter greatly improves developing speed and clarity.  
I suggest adding this to the repo.  
Some options:  
* just formatting
  * [autopep8](https://github.com/hhatto/autopep8)
  * [black](https://github.com/psf/black)
* general linting (might be opinionated in some regards, but usually configurable)
  * [pylint](https://github.com/PyCQA/pylint)
  * [flake8](https://github.com/pycqa/flake8)

**Comment by TitusKirch** [comment]
I have never worked with a linter before, which of the four would you recommend most?


A note for the documentation:
https://code.visualstudio.com/docs/python/linting

**Comment by KnutZuidema** [comment]
I would suggest using `black` for formatting. It's not configurable, which makes it "compatible" from a formatting perspective with every other project that uses `black`.

As for linting I'm not sure which option is better. I've personally used `flake8` more often.
